USE dblojinha;
GO

CREATE TABLE   tblvendas (
    [CODIGO] INT IDENTITY(1,1) NOT NULL,
    [DATA] DATETIME DEFAULT GETDATE(),
    [QUANTIDADE] INT NOT NULL,
    [FATURADO] BIT DEFAULT 0, -- 
    [CODIGOCLIENTE] INT NOT NULL,
    [CODIGOPRODUTO] INT NOT NULL,

    CONSTRAINT [PK_VENDAS] PRIMARY KEY CLUSTERED ([CODIGO]),

    CONSTRAINT [FK_Codigo_Cliente] FOREIGN KEY ([CODIGOCLIENTE]) 
        REFERENCES [CLIENTES] ([CODIGO]),

    CONSTRAINT [FK_Codigo_Produto] FOREIGN KEY ([CODIGOPRODUTO]) 
        REFERENCES [PRODUTOS] ([CODIGO])
) ON [PRIMARY];
GO

SELECT * FROM tblvendas;